- alias: 'Luces Tarde'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 9
  action:
    - condition: state
      entity_id: input_boolean.luztarde
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - service: scene.turn_on
      data_template:
        entity_id: "{%if states.group.familia.state == 'home' %}scene.tarde{% else %}scene.tarde{% endif %}"

- alias: 'Luces Tarde (Finde)'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 4
  condition:
    - condition: state
      entity_id: group.familia
      state: 'home'
    - condition: state
      entity_id: input_boolean.luztarde
      state: 'on'
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: scene.turn_on
    data_template:
      entity_id: "{%if states.group.familia.state == 'home' %}scene.tarde{% else %}scene.tarde{% endif %}"

- alias: 'Entrando en casa'
  trigger:
    platform: state
    entity_id: group.familia
    from: 'not_home'
    to: 'home'
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 6
    - condition: state
      entity_id: input_boolean.entrarsalirdecasa
      state: 'on'
    - condition: or
      conditions:
        - condition: time
          before: '04:00'
        - condition: time
          after: '16:00'
  action:
    service: scene.turn_on
    entity_id: scene.EntradaEnCasa

- alias: 'Entrando en casa (oscura)'
  trigger:
    platform: state
    entity_id: group.familia
    from: 'not_home'
    to: 'home'
  condition:
    - condition: and
      conditions:
          - condition: numeric_state
            entity_id: sensor.sensorluz_7_0
            below: 10
          - condition: numeric_state
            entity_id: sensor.fibaro_system_fgms001_motion_sensor_luminance_2
            below: 15
          - condition: numeric_state
            entity_id: sensor.movyluz_3_1
            below: 10
    - condition: state
      entity_id: input_boolean.entrarsalirdecasa
      state: 'on'
    - condition: or
      conditions:
          - condition: time
            after: '16:00'
          - condition: time
            before: '04:00'
  action:
    service: scene.turn_on
    entity_id: scene.EntradaEnCasa

- alias: 'Saliendo por la tarde'
  trigger:
    platform: state
    entity_id: group.familia
    from: 'home'
    to: 'not_home'
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3
    - condition: time
      after: '17:00'
    - condition: state
      entity_id: input_boolean.entrarsalirdecasa
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.noche

- alias: 'Enciende Salon'
  trigger:
    platform: time
    after: '06:35'
  action:
    service: scene.turn_on
    entity_id: scene.despiertasalon

- alias: 'Enciende Despacho'
  trigger:
    platform: state
    entity_id: sensor.mini_despacho
    to: 'ON'
  condition:
      condition: or
      conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 4
      - condition: numeric_state
        entity_id: sensor.sensorluz_7_0
        value_template: '{{ states.sensor.sensorluz_7_0.state }}'
        below: 10
  action:
    - service: scene.turn_on
      entity_id: scene.DespiertaDespacho

- alias: 'Apaga Despacho'
  trigger:
    platform: state
    entity_id: sensor.mini_despacho
    to: 'OFF'
  condition:
    condition: state
    entity_id: light.lampara_del_despacho
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.apagadespacho

- alias: 'Despertador'
  trigger:
    platform: template
    value_template: '{{ now.time().strftime("%H:%M") == states.input_select.alarma_cuarto.state }}'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.despcuarto
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.despiertacuarto

- alias: 'Baja Luces Cuarto 8:00'
  trigger:
    platform: time
    after: '08:00'
  condition:
    - condition: state
      entity_id: light.mesitaana
      state: 'on'
    - condition: state
      entity_id: light.mesitadani
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.despcuarto
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.BajaLucesCuarto

- alias: 'Saliendo de casa: Apaga Luces'
  trigger:
    platform: state
    entity_id: group.familia
    from: 'home'
    to: 'not_home'
  condition:
    condition: time
    after: '06:00'
    before: '09:00'
  action:
    service: script.turn_on
    entity_id: script.apagaluces

- alias: 'Apaga Luces Mañana (Entre semana)'
  trigger:
    platform: time
    after: '08:30'
  condition:
    - condition: state
      entity_id: group.all_lights
      state: 'on'
    - condition: time
      weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: script.turn_on
    entity_id: script.apagaluces

- alias: 'Apaga Luces Mañana (Finde)'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3
  condition:
    - condition: state
      entity_id: group.all_lights
      state: 'on'
    - condition: time
      weekday:
          - sat
          - sun
  action:
    service: script.turn_on
    entity_id: script.apagaluces

- alias: 'Apaga Luces 1 AM'
  trigger:
    platform: time
    after: '01:00'
  condition:
    condition: state
    entity_id: group.familia
    state: 'not_home'
  action:
    service: script.turn_on
    entity_id: script.apagaluces

###################  PLEX #########################

- alias: 'Play en Salon'
  trigger:
    platform: state
    entity_id: media_player.mini
    to: 'playing'
  condition:
    - condition: state
      entity_id: group.familia
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: or
      conditions:
        - condition: time
          after: '21:45'
        - condition: time
          before: '04:00'
    - condition: state
      entity_id: input_boolean.lucesplex
      state: 'on'
    - condition: state
      entity_id: binary_sensor.contacto_10_0
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.dimsalon

- alias: 'Pausa en Salon'
  trigger:
    platform: state
    entity_id: media_player.mini
    to: 'paused'
  condition:
    - condition: state
      entity_id: group.familia
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: or
      conditions:
        - condition: time
          after: '21:45'
        - condition: time
          before: '04:00'
    - condition: state
      entity_id: input_boolean.lucesplex
      state: 'on'
    - condition: state
      entity_id: binary_sensor.contacto_10_0
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.pausasalon

- alias: 'Stop en Salon'
  trigger:
    platform: state
    entity_id: media_player.mini
    to: 'idle'
  condition:
    - condition: state
      entity_id: group.familia
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: or
      conditions:
        - condition: time
          after: '21:45'
        - condition: time
          before: '04:00'
    - condition: state
      entity_id: input_boolean.lucesplex
      state: 'on'
    - condition: state
      entity_id: binary_sensor.contacto_10_0
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.stopsalon

##################### HARMONY ########################
- alias: 'Hora de dormir'
  trigger:
    platform: state
    entity_id: sensor.harmony
    to: 'OFF'
  # condition_type: or
  condition:
    condition: or
    conditions:
      - condition: time
        after: '22:00'
      - condition: time
        before: '04:00'
  action:
    service: scene.turn_on
    entity_id: scene.horadedormir


############# TRIGGERS DE MOVIMIENTO  ##################

- alias: 'Movimiento -> Enciende lampara del salon'
  trigger:
    platform: state
    entity_id: binary_sensor.movyluz_3_0
    to: 'on'
  condition:
    - condition: state
      entity_id: light.sofa
      state: 'off'
    - condition: state
      entity_id: sensor.harmony
      state: 'OFF'
    - condition: or
      conditions:
        - condition: time
          after: '23:00'
        - condition: time
          before: '06:35'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_lamp

############ MESA CENTRO ###################
- alias: 'Subida Mesita Comedor'
  trigger:
    platform: state
    entity_id: binary_sensor.contacto_10_0
    to: 'on'
  condition:
    - condition: state
      entity_id: light.mueble
      state: 'on'
    - condition: state
      entity_id: input_boolean.lucesmesitacomedor
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '20:00'
  action:
    service: scene.turn_on
    entity_id: scene.SubeLucesComedor

- alias: 'Bajada Mesita Comedor'
  trigger:
    platform: state
    entity_id: binary_sensor.contacto_10_0
    to: 'off'
  condition:
    - condition: state
      entity_id: light.mueble
      state: 'on'
    - condition: state
      entity_id: input_boolean.lucesmesitacomedor
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '20:00'
  action:
    service: scene.turn_on
    entity_id: scene.BajaLucesComedor
############### MOVIMIENTO CUARTO ###################
- alias: 'Entrando al cuarto'
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_2
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.entrarsalircuarto
      state: 'on'
    - condition: state
      entity_id: light.mesitaana
      state: 'on'
    - condition: state
      entity_id: light.mesitadani
      state: 'on'
    - condition: template
      value_template: '{% if states.light.mesitaana %}{{ states.light.mesitaana.attributes.brightness < 200 }}{% else %}false{% endif %}'
    - condition: time
      after: '18:00'
      before: '23:00'
  action:
    service: scene.turn_on
    entity_id: scene.SubeLucesCuarto

- alias: 'Saliendo del cuarto'
  trigger:
    platform: state
    entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_2
    state: 'off'
    for:
      minutes: 1
      seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.entrarsalircuarto
      state: 'on'
    - condition: state
      entity_id: light.mesitaana
      state: 'on'
    - condition: state
      entity_id: light.mesitadani
      state: 'on'
    - condition: template
      value_template: '{% if states.light.mesitaana %}{{ states.light.mesitaana.attributes.brightness > 200 }}{% else %}false{% endif %}'
    - condition: time
      after: '18:00'
      before: '23:00'
  action:
    service: scene.turn_on
    entity_id: scene.BajaLucesCuarto

############### ENTRADA / SALIDA ###################

- alias: 'Alguien entra'
  trigger:
    platform: state
    entity_id: binary_sensor.contacto_1_0
    to: 'on'
  condition:
    - condition: state
      entity_id: group.familia
      state: 'not_home'
  action:
    service: homeassistant.turn_on
    entity_id: script.buscagente

- alias: 'Tal vez entre/salga alguien'
  trigger:
    platform: state
    entity_id: binary_sensor.contacto_1_0
    to: 'on'
  condition:
    - condition: state
      entity_id: group.familia
      state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: script.buscagentequesale

- alias: 'Para de buscar'
  trigger:
    platform: state
    entity_id: group.familia
    from: 'not_home'
    to: 'home'
  action:
    service: homeassistant.turn_off
    entity_id: script.buscagentequesale

############### BATERIA FIBARO ###################
- alias: 'Bateria baja Fibaro FGMS001'
  trigger:
    platform: numeric_state
    entity_id: sensor.fibaro_system_fgms001_motion_sensor_luminance_2
    value_template: '{{ state.attributes.battery_level }}'
    below: 10
  action:
    service: notify.notifica
    data:
      message: 'La bateria del sensor Fibaro esta baja'
